version: '3.7'

services:

  app:
    container_name: Docker-Web-Streaming
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      -  80:80
    environment:
      - NODE_ENV=development